language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - TYPE=Debug

    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
      
before_install:
  - eval "${MATRIX_EVAL}"
  - git clone -brelease-2 https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_packages.sh
  - bash ./emp-readme/scripts/install_emp-tool.sh
  - cd emp-tool; cmake -DENABLE_FLOAT=On .; sudo make install; cd ..
  - bash ./emp-readme/scripts/install_emp-ot.sh

script:
  - cmake -DCMAKE_BUILD_TYPE=$TYPE -DENABLE_FLOAT=On . && make 
  - ./run ./bin/bit
  - ./run ./bin/int
  - ./run ./bin/float
